name: âš¡ Prod | Client | Manual
on: [workflow_dispatch]

jobs:
  web-deploy:
    name: ðŸŽ‰ Manual Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ“© Check Out Code
        uses: actions/checkout@v4.1.1

      - name: ðŸ¥· Use Node.js 20.18.1
        uses: actions/setup-node@v6
        with:
          node-version: '20.18.1'

      - name: ðŸ’¥ Install & Cache Deps
        uses: bahmutov/npm-install@v1.11.2
        with:
          working-directory: client

      - name: ðŸ§¹ Lint Build
        run: npm run lint
        working-directory: client

      - name: ðŸ§ª Test Build
        run: npm test
        working-directory: client

      - name: ðŸ”¨ Build Project
        run: INLINE_RUNTIME_CHUNK=false npm run build
        working-directory: client

      - name: ðŸ“‚ Sync files
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_QUICKDASH_4BF3A }}
          firebaseToolsVersion: 15.1.0
          projectId: quickdash-4bf3a
          target: list-quickdash
          channelId: live
          force: true
